# Generated by Django 5.0.3 on 2024-04-21 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productType', models.CharField(max_length=75)),
                ('productbrand', models.CharField(max_length=75)),
                ('productModel', models.CharField(max_length=75)),
                ('prductProblemDescription', models.CharField(max_length=75)),
            ],
        ),
    ]
