# Generated by Django 5.0.3 on 2024-05-11 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_client', '0002_orderrequest_delete_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrequest',
            name='status',
            field=models.CharField(choices=[('EM_ANALISE', 'Em análise'), ('AGENDADO', 'Agendado'), ('AGUARDANDO_ORCAMENTO', 'Aguardando orçamento'), ('AGUARDANDO_CONFIRMACAO', 'Aguardando confirmação'), ('ACEITO', 'Aceito'), ('RECUSADO', 'Recusado'), ('CANCELADA', 'Cancelada')], default='EM_ANALISE', max_length=30),
        ),
    ]
