# Generated by Django 5.0.3 on 2024-05-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_client', '0003_orderrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrequest',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
