# Generated by Django 5.0.3 on 2024-05-14 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_client', '0006_orderrequest_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
