# Generated by Django 5.0.3 on 2024-05-17 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_client', '0007_orderrequest_created_at_orderrequest_scheduled_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrequest',
            name='isOs',
            field=models.BooleanField(default=False),
        ),
    ]
