# Generated by Django 5.0.3 on 2024-05-17 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_client', '0008_orderrequest_isos'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrequest',
            name='closedAt',
            field=models.DateField(blank=True, null=True),
        ),
    ]
