# Generated by Django 5.0.3 on 2024-05-20 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_client', '0009_orderrequest_closedat'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.IntegerField()),
                ('time', models.IntegerField()),
                ('service', models.IntegerField()),
                ('notes', models.CharField(max_length=200)),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_client.orderrequest')),
            ],
        ),
    ]
