# Generated by Django 5.0.3 on 2024-06-04 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_client', '0011_alter_servicerating_attendance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrequest',
            name='isReopen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='reopen_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
