# Generated by Django 5.0.3 on 2024-04-16 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('A', 'Administrador'), ('F', 'Funcionario'), ('C', 'Cliente')], max_length=1),
        ),
    ]
