# Generated by Django 5.0.3 on 2024-04-22 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_company', '0005_users_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='position',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
