# Generated by Django 5.0.3 on 2024-04-22 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_company', '0006_users_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
