# Generated by Django 5.0.3 on 2024-04-24 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_company', '0008_remove_users_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='number',
            field=models.CharField(default='', max_length=10, null=True),
        ),
    ]
