# Generated by Django 5.0.3 on 2024-05-12 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_company', '0010_serviceorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceOrder',
        ),
    ]
