# Generated by Django 5.0.3 on 2024-05-13 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_company', '0011_delete_serviceorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='password_was_changed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
