# Generated by Django 5.0.3 on 2024-05-13 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_company', '0012_users_password_was_changed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='password_was_changed',
            field=models.BooleanField(default=False),
        ),
    ]
